version: "2"
volumes:
  oc-data:
    driver: ${VOLUME_DRIVER}
  oc-config-admin:
    driver: ${VOLUME_DRIVER}
  oc-config-presentation:
    driver: ${VOLUME_DRIVER}
  oc-config-worker:
    driver: ${VOLUME_DRIVER}
  oc-deploy-admin:
    driver: ${VOLUME_DRIVER}
  oc-deploy-presentation:
    driver: ${VOLUME_DRIVER}
  oc-deploy-worker:
    driver: ${VOLUME_DRIVER}
  db:
    driver: ${VOLUME_DRIVER}
  activemq:
    driver: ${VOLUME_DRIVER}


services:
  mariadb:
    image: registry.oc.univie.ac.at/amc/ocm-mariadb:${OC_IMAGE_VERSION}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}

  activemq:
    image: registry.oc.univie.ac.at/amc/ocm-activemq:${OC_IMAGE_VERSION}
    environment:
#      - ACTIVEMQ_MIN_MEMORY=128
#      - ACTIVEMQ_MAX_MEMORY=1024


  opencast-admin:
    image: registry.oc.univie.ac.at/amc/ocm-admin:${OC_IMAGE_VERSION}
    labels:
      io.rancher.container.pull_image: always
    environment:
      - ORG_OPENCASTPROJECT_SERVER_URL=${OC_ADMIN_SERVER_URL}
      - TENANT1_ID=${OC_TENANT1_ID}
      - TENANT1_NAME=${OC_TENANT1_NAME}
      - TENANT2_ID=${OC_TENANT2_ID}
      - TENANT2_NAME=${OC_TENANT2_NAME}
      - OPENCAST_DATA=${OC_DATA}
      - ORG_OPENCASTPROJECT_ADMIN_EMAIL=${OC_ADMIN-EMAIL}
      - ORG_OPENCASTPROJECT_DOWNLOAD_URL=${OC_DOWNLOAD_URL}
      - PROP_ORG_OPENCASTPROJECT_FILE_REPO_URL=${OC_ADMIN_SERVER_URL}
      - ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER=${OC_ADMIN-USER}
      - ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS=${OC_ADMIN-PASS}
      - ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER=${OC_DIGEST_USER}
      - ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS=${OC_DIGEST_PASS}
      - ORG_OPENCASTPROJECT_DB_VENDOR=MySQL
      - ORG_OPENCASTPROJECT_DB_JDBC_URL=jdbc:mysql://mariadb/${DB_NAME}
      - ORG_OPENCASTPROJECT_DB_JDBC_USER=${DB_USER}
      - ORG_OPENCASTPROJECT_DB_JDBC_PASS=${DB_USER_PASSWORD}
      - ORG_OPENCASTPROJECT_DB_DDL_GENERATION="false"
      - PROP_ORG_OPENCASTPROJECT_ADMIN_UI_URL=${OC_ADMIN_SERVER_URL}
      - PROP_ORG_OPENCASTPROJECT_TENANT1_ADMIN_UI_URL=${OC_TENANT1-ADMIN-URL}
      - PROP_ORG_OPENCASTPROJECT_TENANT2_ADMIN_UI_URL=${OC_TENANT2-ADMIN-URL}
      - PROP_ORG_OPENCASTPROJECT_ENGAGE_UI_URL=${OC_PRESENTATION_SERVER_URL}
      - PROP_ORG_OPENCASTPROJECT_TENANT1_PRESENTATION_UI_URL=${OC_TENANT1-PRESENTATION-URL}
      - PROP_ORG_OPENCASTPROJECT_TENANT2_PRESENTATION_UI_URL==${OC_TENANT2-PRESENTATION-URL}
      - ACTIVEMQ_BROKER_URL=failover://(tcp://activemq:61616)?initialReconnectDelay=2000&maxReconnectAttempts=2
      - ACTIVEMQ_BROKER_USERNAME=admin
      - ACTIVEMQ_BROKER_PASSWORD=password
    links:
      - "mariadb"
      - "activemq"
    volumes:
      - oc-data:/data

  opencast-presentation:
    image: registry.oc.univie.ac.at/amc/ocm-presentation:${OC_IMAGE_VERSION}
    labels:
      io.rancher.container.pull_image: always
    environment:
      - ORG_OPENCASTPROJECT_SERVER_URL=${OC_PRESENTATION_SERVER_URL}
      - ORG_OPENCASTPROJECT_DOWNLOAD_URL=${OC_DOWNLOAD_URL}
      - ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER=${OC_ADMIN-USER}
      - ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS=${OC_ADMIN-PASS}
      - ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER=${OC_DIGEST_USER}
      - ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS=${OC_DIGEST_PASS}
      - ORG_OPENCASTPROJECT_DB_VENDOR=MySQL
      - ORG_OPENCASTPROJECT_DB_JDBC_URL=jdbc:mysql://mariadb/${DB_NAME}
      - ORG_OPENCASTPROJECT_DB_JDBC_USER=${DB_USER}
      - ORG_OPENCASTPROJECT_DB_JDBC_PASS=${DB_USER_PASSWORD}
      - PROP_ORG_OPENCASTPROJECT_ADMIN_UI_URL=${OC_ADMIN_UI_URL}
      - PROP_ORG_OPENCASTPROJECT_ENGAGE_UI_URL=${OC_PRESENTATION_SERVER_URL}
      - ACTIVEMQ_BROKER_URL=failover://(tcp://activemq:61616)?initialReconnectDelay=2000&maxReconnectAttempts=2
      - ACTIVEMQ_BROKER_USERNAME=admin
      - ACTIVEMQ_BROKER_PASSWORD=password
    links:
      - "opencast-admin"
      - "mariadb"
      - "activemq"
    volumes:
      - oc-data:/data

  opencast-worker:
    image: registry.oc.univie.ac.at/amc/ocm-worker:${OC_IMAGE_VERSION}
    labels:
      io.rancher.container.pull_image: always
    environment:
    #  - ORG_OPENCASTPROJECT_SERVER_URL=http://opencast-worker:8080
      - ORG_OPENCASTPROJECT_DOWNLOAD_URL=${OC_DOWNLOAD_URL}
      - ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER=${OC_ADMIN-USER}
      - ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS=${OC_ADMIN-PASS}
      - ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER=${OC_DIGEST_USER}
      - ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS=${OC_DIGEST_PASS}
      - ORG_OPENCASTPROJECT_DB_VENDOR=MySQL
      - ORG_OPENCASTPROJECT_DB_JDBC_URL=jdbc:mysql://mariadb/${DB_NAME}
      - ORG_OPENCASTPROJECT_DB_JDBC_USER=${DB_USER}
      - ORG_OPENCASTPROJECT_DB_JDBC_PASS=${DB_USER_PASSWORD}
      - PROP_ORG_OPENCASTPROJECT_ADMIN_UI_URL=${OC_ADMIN_UI_URL}
      - PROP_ORG_OPENCASTPROJECT_ENGAGE_UI_URL=${OC_PRESENTATION_SERVER_URL}
      - ACTIVEMQ_BROKER_URL=failover://(tcp://activemq:61616)?initialReconnectDelay=2000&maxReconnectAttempts=2
      - ACTIVEMQ_BROKER_USERNAME=admin
      - ACTIVEMQ_BROKER_PASSWORD=password
    links:
      - "opencast-admin"
      - "mariadb"
      - "activemq"
    volumes:
      - oc-data:/data
