version: "2"
volumes:
  oc-data:
  oc-config-admin:
  oc-config-presentation:
  oc-config-worker:
  oc-deploy-admin:
  oc-deploy-presentation:
  oc-deploy-worker:
  db:
  activemq:


services:
  mariadb:
    image: opencast-mt-mariadb:${TAG}
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
#    links:
#      - "config"
    volumes:
      - db:/var/lib/mysql
  activemq:
    image: opencast-mt-activemq:${TAG}
#    environment:
#      - ACTIVEMQ_MIN_MEMORY=128
#      - ACTIVEMQ_MAX_MEMORY=1024
#      - ACTIVEMQ_ENABLED_SCHEDULER=true
#      - ACTIVEMQ_REMOVE_DEFAULT_ACCOUNT=true
#      - ACTIVEMQ_OWNER_LOGIN=admin
#      - ACTIVEMQ_OWNER_PASSWORD=password
#    links:
#      - "config"
    volumes:
      - activemq:/opt/activemq/conf

  opencast-admin:
    image: opencast-mt-admin:${TAG}
#    labels:
#      io.rancher.container.pull_image: always
    environment:
      - ORG_OPENCASTPROJECT_SERVER_URL=${OC_ADMIN_SERVER_URL}
      - TENANT1_ID=${OC_TENANT1_ID}
      - TENANT1_NAME=${OC_TENANT1_NAME}
      - TENANT2_ID=${OC_TENANT2_ID}
      - TENANT2_NAME=${OC_TENANT2_NAME}
      - OPENCAST_DATA=${OC_DATA}
      - ORG_OPENCASTPROJECT_ADMIN_EMAIL=${OC_ADMIN_SERVER_URL}
      - ORG_OPENCASTPROJECT_DOWNLOAD_URL=${OC_ADMIN_SERVER_URL}
      - PROP_ORG_OPENCASTPROJECT_FILE_REPO_URL=${OC_ADMIN_SERVER_URL}
      - ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER=${OC_ADMIN_USER}
      - ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS=${OC_ADMIN_PASS}
      - ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER=${OC_DIGEST_USER}
      - ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS=${OC_DIGEST_PASS}
      - ORG_OPENCASTPROJECT_DB_VENDOR=MySQL
      - ORG_OPENCASTPROJECT_DB_JDBC_URL=jdbc:mysql://mariadb/${MYSQL_DATABASE}
      - ORG_OPENCASTPROJECT_DB_JDBC_USER=${MYSQL_USER}
      - ORG_OPENCASTPROJECT_DB_JDBC_PASS=${MYSQL_PASSWORD}
      - ORG_OPENCASTPROJECT_DB_DDL_GENERATION="false"
      - PROP_ORG_OPENCASTPROJECT_ADMIN_UI_URL=${OC_ADMIN_SERVER_URL}
      - PROP_ORG_OPENCASTPROJECT_TENANT1_ADMIN_UI_URL=${OC_TENANT1_ADMIN_URL}
      - PROP_ORG_OPENCASTPROJECT_TENANT2_ADMIN_UI_URL=${OC_TENANT2_ADMIN_URL}
      - PROP_ORG_OPENCASTPROJECT_ENGAGE_UI_URL=${OC_PRESENTATION_SERVER_URL}
      - PROP_ORG_OPENCASTPROJECT_TENANT1_PRESENTATION_UI_URL=${OC_TENANT1_PRESENTATION_URL}
      - PROP_ORG_OPENCASTPROJECT_TENANT2_PRESENTATION_UI_URL=${OC_TENANT2_PRESENTATION_URL}
      - ACTIVEMQ_BROKER_URL=failover://(tcp://activemq:61616)?initialReconnectDelay=2000&maxReconnectAttempts=2
      - ACTIVEMQ_BROKER_USERNAME=admin
      - ACTIVEMQ_BROKER_PASSWORD=password
    links:
      - "mariadb"
      - "activemq"
      - "config"
    ports:
      - "8080:8080"
    volumes:
      - oc-data:/data
      - oc-config-admin:/opt/opencast/etc
      - oc-deploy-admin:/opt/opencast/deploy

  opencast-presentation:
    image: opencast-mt-presentation:${TAG}
    environment:
      - ORG_OPENCASTPROJECT_SERVER_URL=${OPENCAST_PRESENTATION_URL}
      - TENANT1_ID=${OC_TENANT1_ID}
      - TENANT1_NAME=${OC_TENANT1_NAME}
      - TENANT2_ID=${OC_TENANT2_ID}
      - TENANT2_NAME=${OC_TENANT2_NAME}
      - OPENCAST_DATA=${OC_DATA}
      - ORG_OPENCASTPROJECT_ADMIN_EMAIL=${OC_ADMIN_EMAIL}
      - ORG_OPENCASTPROJECT_DOWNLOAD_URL=${OC_ADMIN_SERVER_URL}
      - PROP_ORG_OPENCASTPROJECT_FILE_REPO_URL=${OC_ADMIN_SERVER_URL}
      - ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER=${OC_ADMIN_USER}
      - ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS=${OC_ADMIN_PASS}
      - ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER=${OC_DIGEST_USER}
      - ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS=${OC_DIGEST_PASS}
      - ORG_OPENCASTPROJECT_DB_VENDOR=MySQL
      - ORG_OPENCASTPROJECT_DB_JDBC_URL=jdbc:mysql://mariadb/${MYSQL_DATABASE}
      - ORG_OPENCASTPROJECT_DB_JDBC_USER=${MYSQL_USER}
      - ORG_OPENCASTPROJECT_DB_JDBC_PASS=${MYSQL_PASSWORD}
      - ORG_OPENCASTPROJECT_DB_DDL_GENERATION="false"
      - PROP_ORG_OPENCASTPROJECT_ADMIN_UI_URL=${OC_ADMIN_SERVER_URL}
      - PROP_ORG_OPENCASTPROJECT_TENANT1_ADMIN_UI_URL=${OC_TENANT1_ADMIN_URL}
      - PROP_ORG_OPENCASTPROJECT_TENANT2_ADMIN_UI_URL=${OC_TENANT2_ADMIN_URL}
      - PROP_ORG_OPENCASTPROJECT_ENGAGE_UI_URL=${OC_PRESENTATION_SERVER_URL}
      - PROP_ORG_OPENCASTPROJECT_TENANT1_PRESENTATION_UI_URL=${OC_TENANT1_PRESENTATION_URL}
      - PROP_ORG_OPENCASTPROJECT_TENANT2_PRESENTATION_UI_URL=${OC_TENANT2_PRESENTATION_URL}
      - ACTIVEMQ_BROKER_URL=failover://(tcp://activemq:61616)?initialReconnectDelay=2000&maxReconnectAttempts=2
      - ACTIVEMQ_BROKER_USERNAME=admin
      - ACTIVEMQ_BROKER_PASSWORD=password
    ports:
      - "8081:8080"
    links:
      - "opencast-admin"
      - "mariadb"
      - "activemq"
      - "config"
    volumes:
      - oc-data:/data
      - oc-config-presentation:/opt/opencast/etc
      - oc-deploy-presentation:/opt/opencast/deploy

  opencast-worker:
    image: opencast-mt-worker:${TAG}
    environment:
#      - ORG_OPENCASTPROJECT_SERVER_URL=http://opencast-worker:8080
      - TENANT1_ID=${OC_TENANT1_ID}
      - TENANT1_NAME=${OC_TENANT1_NAME}
      - TENANT2_ID=${OC_TENANT2_ID}
      - TENANT2_NAME=${OC_TENANT2_NAME}
      - OPENCAST_DATA=${OC_DATA}
      - ORG_OPENCASTPROJECT_ADMIN_EMAIL=${OC_ADMIN_EMAIL}
      - ORG_OPENCASTPROJECT_DOWNLOAD_URL=${OC_ADMIN_SERVER_URL}
      - PROP_ORG_OPENCASTPROJECT_FILE_REPO_URL=${OC_ADMIN_SERVER_URL}
      - ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER=${OC_ADMIN_USER}
      - ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS=${OC_ADMIN_PASS}
      - ORG_OPENCASTPROJECT_SECURITY_DIGEST_USER=${OC_DIGEST_USER}
      - ORG_OPENCASTPROJECT_SECURITY_DIGEST_PASS=${OC_DIGEST_PASS}
      - ORG_OPENCASTPROJECT_DB_VENDOR=MySQL
      - ORG_OPENCASTPROJECT_DB_JDBC_URL=jdbc:mysql://mariadb/${MYSQL_DATABASE}
      - ORG_OPENCASTPROJECT_DB_JDBC_USER=${MYSQL_USER}
      - ORG_OPENCASTPROJECT_DB_JDBC_PASS=${MYSQL_PASSWORD}
      - ORG_OPENCASTPROJECT_DB_DDL_GENERATION="false"
      - PROP_ORG_OPENCASTPROJECT_ADMIN_UI_URL=${OC_ADMIN_SERVER_URL}
      - PROP_ORG_OPENCASTPROJECT_TENANT1_ADMIN_UI_URL=${OC_TENANT1_ADMIN_URL}
      - PROP_ORG_OPENCASTPROJECT_TENANT2_ADMIN_UI_URL=${OC_TENANT2_ADMIN_URL}
      - PROP_ORG_OPENCASTPROJECT_ENGAGE_UI_URL=${OC_PRESENTATION_SERVER_URL}
      - PROP_ORG_OPENCASTPROJECT_TENANT1_PRESENTATION_UI_URL=${OC_TENANT1_PRESENTATION_URL}
      - PROP_ORG_OPENCASTPROJECT_TENANT2_PRESENTATION_UI_URL=${OC_TENANT2_PRESENTATION_URL}
      - ACTIVEMQ_BROKER_URL=failover://(tcp://activemq:61616)?initialReconnectDelay=2000&maxReconnectAttempts=2
      - ACTIVEMQ_BROKER_USERNAME=admin
      - ACTIVEMQ_BROKER_PASSWORD=password
    links:
      - "opencast-admin"
      - "mariadb"
      - "activemq"
      - "config"
    volumes:
      - oc-data:/data
      - oc-config-worker:/opt/opencast/etc
      - oc-deploy-worker:/opt/opencast/deploy

  config:
    image: opencast-mt-config:${TAG}
    volumes:
      - oc-data:/data
      - oc-config-admin:/opt/opencast/etc/admin
      - oc-deploy-admin:/opt/opencast/deploy/admin
      - oc-config-presentation:/opt/opencast/etc/presentation
      - oc-deploy-presentation:/opt/opencast/deploy/presentation
      - oc-config-worker:/opt/opencast/etc/worker
      - oc-deploy-worker:/opt/opencast/deploy/worker
#      - /volumes/opencast-config-ssh:/opt/opencast/.ssh
      - db:/opt/opencast/db
      - activemq:/opt/opencast/activemq

    ports:
      - "22422:22"
