FROM openjdk:8-jdk-slim-stretch

ARG repo="https://github.com/opencast/opencast.git"
ARG branch="4.3"

ENV LANG="C.UTF-8" \
#    JAVA_HOME="/usr/lib/jvm/java-1.8-openjdk" \
#    PATH="$PATH:/usr/lib/jvm/java-1.8-openjdk/jre/bin:/usr/lib/jvm/java-1.8-openjdk/bin" \
    HUNSPELL_BASE_URL="http://download.services.openoffice.org/contrib/dictionaries" \
    OPENCAST_SRC="/usr/src/opencast" \
    OPENCAST_BUILD="/opencast" \
    OPENCAST_UID="800" \
    OPENCAST_GID="800" \
    OPENCAST_REPO="${repo}" \
    OPENCAST_BRANCH="${branch}" \
    OPENCAST_VERSION="${branch}" \
    OPENCAST_CONFIG_GIT="https://schambm7:k3m2zbfe@bitbucket.org/schambm7/oc-univie-config.git"

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
      tar gzip git \
      ca-certificates openssl \
      maven make gcc g++ libc-dev
RUN mkdir -p "${OPENCAST_SRC}" "${OPENCAST_BUILD}"
RUN git clone --recursive "${OPENCAST_REPO}" "${OPENCAST_SRC}" && \
    cd "${OPENCAST_SRC}" && \
    git checkout "${OPENCAST_BRANCH}"
RUN cd "${OPENCAST_SRC}" && \
    mvn --batch-mode install -DskipTests=true -Dcheckstyle.skip=true -DskipJasmineTests=true


#WORKDIR "${OPENCAST_HOME}"/build
#RUN ln -s "${OPENCAST_SRC}"/build/*.tar.gz . && chown -R "${OPENCAST_UID}":"${OPENCAST_GID}" *
#VOLUME ['/build/']
#RUN rm -rf "${OPENCAST_SRC}" /tmp/* /var/lib/apt/lists/* ~/.m2 ~/.npm ~/.node-gyp /usr/lib/node_modules
