.catalog:
  name: "Opencast Multitenant Installation"
  version: "0.1"
  description: "Host your Opencast with multiple tenants"
  minimum_rancher_version: v1.6.0
## VOLUMES
  questions:
    - variable: VOLUME_DRIVER
      description: "The Volume driver to associate with this registry"
      label: "Volume Driver"
      type: enum
      required: true
      default: "local"
      options:
        - local
        - rancher-nfs
        - external

# ENVIRONMENT VARIABLES
# MariaDB
    - variable: DB_ROOT_PASSWORD
      description: "Password for Root on MariaDB"
      label: "MariaDB: Root Password"
      type: password
      required: true
      default: "livestream"
    - variable: DB_NAME
      description: "Password for Root on MariaDB"
      label: "MariaDB: Databasename for Opencast"
      type: string
      required: true
      default: "opencast"
    - variable: DB_USER
      description: "User running DB for Opencast"
      label: "MariaDB: User"
      type: string
      required: true
      default: "opencast"
    - variable: DB_USER_PASSWORD
      description: "Password for User on MariaDB"
      label: "MariaDB: User Password"
      type: password
      required: true
      default: "opencast"
# ActiveMQ
#      - ACTIVEMQ_MIN_MEMORY=128
#      - ACTIVEMQ_MAX_MEMORY=1024

# Opencast

    - variable: OC_ADMIN_SERVER_URL
      description: "Server URL of Admin-Node - is also running default tenant"
      label: "Opencast Admin Server URL"
      type: string
      required: true
      default: "oc-admin"
    - variable: OC_PRESENTATION_SERVER_URL
      description: "Server URL of Presentation-Node - is also running default tenant"
      label: "Opencast Admin Server URL"
      type: string
      required: true
      default: "oc-presentation"
    - variable: OC_DOWNLOAD_URL
      description: "Server URL for Download - usually identical to 'Opencast Admin Server URL'"
      label: "Server URL for Downloads"
      type: string
      required: true
      default: "oc-admin"
    - variable: ORG_OPENCASTPROJECT_SECURITY_ADMIN_USER
      description: Name of admin user in Opencast
      label: "Opencast Admin User"
      type: string
      required: true
      default: "admin"
    - variable: ORG_OPENCASTPROJECT_SECURITY_ADMIN_PASS
      description: "Password of admin user in Opencast"
      label: "Opencast Admin User Password"
      type: string
      required: true
      default: "opencast"
    - variable: OC_ADMIN-EMAIL
      description: "E-Mail-address for admin user"
      label: "Admin E-Mail"
      type: string
      required: true
      default: "admin@localhost"
    - variable: OC_DIGEST_USER
      description: "Name of digest user in Opencast"
      label: "Opencast Digest User"
      type: string
      required: true
      default: "opencast_system_account"
    - variable: OC_DIGEST_PASS
      description: "Password of digest user in Opencast"
      label: "Opencast Digest User"
      type: password
      required: true
      default: "livestream"

    - variable: OC_TENANT1_ID
      description: "ID of the first tenant"
      label: "Tenant 1 ID"
      type: string
      required: true
      default: "tenant1"
    - variable: OC_TENANT1_NAME
      description: "Name that will be used for the first tenant"
      label: "Tenant 1 Name"
      type: string
      required: true
      default: "Tenant 1"
    - variable: OC_TENANT2_ID
      description: "ID of the second tenant"
      label: "Tenant 2 ID"
      type: string
      required: true
      default: "tenant2"
    - variable: OC_TENANT2_NAME
      description: "Name that will be used for the second tenant"
      label: "Tenant 2 Name"
      type: string
      required: true
      default: "Tenant 2"

    - variable: OC_DATA
      description: "Directory used for storing Opencast Data"
      label: "Opencast Data Directory"
      type: string
      required: true
      default: "/data"

    - variable: OC_TENANT1-ADMIN-URL
      description: "Admin URL for the first tenant"
      label: "Tenant 1 Admin UI URL"
      type: string
      required: true
      default: "oc1-admin"
    - variable: OC_TENANT2-ADMIN-URL
      description: "Admin URL for the second tenant"
      label: "Tenant 2 Admin UI URL"
      type: string
      required: true
      default: "oc2-admin"
    - variable: OC_TENANT1-PRESENTATION-URL
      description: "Presentation URL for the first tenant"
      label: "Tenant 1 Presentation UI URL"
      type: string
      required: true
      default: "oc1-presentation"
    - variable: OC_TENANT2-PRESENTATION-URL
      description: "Presentation URL for the second tenant"
      label: "Tenant 2 Presentation UI URL"
      type: string
      required: true
      default: "oc2-presentation"

registry:
  scale: 1
  health_check:
    port: 5000
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 3
    response_timeout: 5000
portus:
  scale: 1
  health_check:
    port: 3000
    interval: 5000
    unhealthy_threshold: 3
    strategy: recreate
    healthy_threshold: 3
    response_timeout: 5000
