apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.8.0 (0c0c027)
  creationTimestamp: null
  labels:
    io.kompose.service: config
  name: config
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: config
    spec:
      containers:
      - image: opencast-mt-config:latest
        name: config
        ports:
        - containerPort: 22
        resources: {}
        volumeMounts:
        - mountPath: /data
          name: oc-data
        - mountPath: /opt/opencast/etc/admin
          name: oc-config-admin
        - mountPath: /opt/opencast/deploy/admin
          name: oc-deploy-admin
        - mountPath: /opt/opencast/etc/presentation
          name: oc-config-presentation
        - mountPath: /opt/opencast/deploy/presentation
          name: oc-deploy-presentation
        - mountPath: /opt/opencast/etc/worker
          name: oc-config-worker
        - mountPath: /opt/opencast/deploy/worker
          name: oc-deploy-worker
        - mountPath: /opt/opencast/db
          name: db
        - mountPath: /opt/opencast/activemq
          name: activemq
      restartPolicy: Always
      volumes:
      - name: oc-data
        persistentVolumeClaim:
          claimName: oc-data
      - name: oc-config-admin
        persistentVolumeClaim:
          claimName: oc-config-admin
      - name: oc-deploy-admin
        persistentVolumeClaim:
          claimName: oc-deploy-admin
      - name: oc-config-presentation
        persistentVolumeClaim:
          claimName: oc-config-presentation
      - name: oc-deploy-presentation
        persistentVolumeClaim:
          claimName: oc-deploy-presentation
      - name: oc-config-worker
        persistentVolumeClaim:
          claimName: oc-config-worker
      - name: oc-deploy-worker
        persistentVolumeClaim:
          claimName: oc-deploy-worker
      - name: db
        persistentVolumeClaim:
          claimName: db
      - name: activemq
        persistentVolumeClaim:
          claimName: activemq
status: {}
